## 데이터 정보 확인
데이터를 분석하려면 일단 데이터가 어떻게 생겼는지. 어떤정보들이 있는지..
자료형은 무엇인지..등 데이터를 이해하는 과정이 가장 먼저 수행됨.

In [1]:
#데이터프레임 만들기
import pandas as pd

data = {
    '이름' : ['손흥민', '김민재', '이강인', '황의찬', '류현진', '김병현', '박찬호', '추신수'],
    '학교' : ['축구고', '축구고', '축구고', '축구고', '야구고', '야구고', '야구고', '야구고'],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90]
}
df= pd.DataFrame(data)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [2]:
# 계산 가능한 수치형 데이터에 대해 개수, 평균, 표준편차, 사분위값, 최대,최소 등을 한눈에 보기
df.describe()

               국어          영어          수학
count    8.000000    8.000000    8.000000
mean    62.500000   65.625000   66.250000
std     29.519969   26.917533   30.325614
min     15.000000   20.000000   10.000000
25%     40.000000   53.750000   48.750000
50%     67.500000   70.000000   70.000000
75%     82.500000   85.000000   91.250000
max    100.000000  100.000000  100.000000

In [3]:
# 데이터의 행개수, 컬룸정보, 개수, 자료형 등 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      object
 1   학교      8 non-null      object
 2   국어      8 non-null      int64
 3   영어      8 non-null      int64
 4   수학      8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 452.0+ bytes

In [4]:
# 데이터프레임의 값들만 확인 - 
df.values

array([['손흥민', '축구고', 90, 85, 100],
       ['김민재', '축구고', 40, 35, 50],
       ['이강인', '축구고', 80, 75, 70],
       ['황의찬', '축구고', 40, 60, 70],
       ['류현진', '야구고', 15, 20, 10],
       ['김병현', '야구고', 80, 100, 95],
       ['박찬호', '야구고', 55, 65, 45],
       ['추신수', '야구고', 100, 85, 90]], dtype=object)

In [5]:
#인덱스 정보 확인
df.index

RangeIndex(start=0, stop=8, step=1)

In [6]:
#컬룸 정보
df.columns

Index(['이름', '학교', '국어', '영어', '수학'], dtype='object')

In [7]:
#행렬 모양
df.shape

(8, 5)

In [8]:
#데이터프레이서 특정 컬룸을 시리즈로 뽑기
df['국어']

0     90
1     40
2     80
3     40
4     15
5     80
6     55
7    100
Name: 국어, dtype: int64

In [9]:
#시리즈 타입도 기초통계기능 함수가 존재함
df['국어'].describe()

count      8.000000
mean      62.500000
std       29.519969
min       15.000000
25%       40.000000
50%       67.500000
75%       82.500000
max      100.000000
Name: 국어, dtype: float64

In [10]:
#각 계산기능함수를 개별사용 가능
df['국어'].mean()

np.float64(62.5)

In [11]:
df['국어'].sum()

np.int64(500)

In [12]:
df['국어'].max()

100

In [13]:
df['학교'].unique()

array(['축구고', '야구고'], dtype=object)

In [14]:
df['학교'].nunique()

2