# Pandas
데이터분석 작업을 용이하게 해주는 파이썬 모듈(라이브러리)
> 2차원 표형태의 데이터를 아주 편하게 처리해주는 모듈    
> 데이터분석 할때 n차원 행렬의 구조로 용이하게 만들어주는 모듈 *(엑셀, csv, tsv 데이터 처리에 용이)*

In [1]:
#0. pandas 모듈 사용
import pandas as pd

### 판다스의 데이터 구조

- **Series 시리즈**   
순차데이터를 저장하는 1차원 배열로 구성
>예 : [10,20,30]

- **DataFrame 데이터프레임**   
행렬로 구성된 2차원 배열로 구성. 각 열에 서로 다른 타입의 데이터로 구성 가능
>예 : [ ['sam',20],['robin',25] ]

#### 1) Series 시리즈  
1차원 배열 구조

In [2]:
aa= pd.Series([10,20,30])
print(aa)  #인덱스번호가 자동부여, 자료형(dtype)이 표시됨

0    10
1    20
2    30
dtype: int64

In [3]:
#시리즈의 출력을 print()없이 시도해도 결과는 같음
aa

0    10
1    20
2    30
dtype: int64

In [4]:
#실수형 데이터 시리즈
bb= pd.Series([3.14, 5.25, 7.0])
print(bb)

0    3.14
1    5.25
2    7.00
dtype: float64

In [6]:
#문자형 데이터 시리즈
cc= pd.Series(['sam','robin','hong']) #pandas에서는 문자형의 자료형을 object
print(cc)

0      sam
1    robin
2     hong
dtype: object

In [7]:
#만약, 타입이 다른 데이터를 시리즈로 만들면?
dd= pd.Series([100,3.14,'park'])
print(dd)

0     100
1    3.14
2    park
dtype: object

In [9]:
#시리즈를 만들때 자료형을 미리 고정할 수 있음.
#ee= pd.Series([100,200,'NaN'], dtype='int64') #error
ee= pd.Series([100,200,300], dtype='int64') #OK
print(ee)

0    100
1    200
2    300
dtype: int64

In [11]:
#인덱스번호를 다른 식별자로 지정할 수 있음.
ff= pd.Series(['seoul','tokyo','paris'], index=['korea','japan','france'])
print(ff)

korea     seoul
japan     tokyo
france    paris
dtype: object

In [12]:
#특정 데이터를 추출하는 인덱싱에 번호가 아닌 식별자를 사용
ff['france']

'paris'

In [13]:
# 시리즈의 자료형 확인
print( type(ff) )

<class 'pandas.core.series.Series'>

In [14]:
# 시리즈의 요소개수(모양)을 알 수 있는 속성
ff.shape

(3,)

#### 시리즈 사용
예) 1월부터 6월까지 평균 온도 데이터 (-10, -5, 4, 10, 20, 25 )

In [15]:
temp= pd.Series([-10, -5, 4, 10, 20, 25])
print(temp)

0   -10
1    -5
2     4
3    10
4    20
5    25
dtype: int64

In [17]:
# 1월 온도 정보 추출하기
print(temp[0])

-10

In [18]:
# 5월 온도 확인
print(temp[4])

20

In [19]:
#인덱스번호를 사용하니 특정 월에 대한 식별이 조금 어려움.
#index명을 각 월의 약어 표현으로 지정
temp= pd.Series([-10, -5, 4, 10, 20, 25], index=['Jan','Feb','Mar','Ari','May','Jun'])
temp

Jan   -10
Feb    -5
Mar     4
Ari    10
May    20
Jun    25
dtype: int64

In [20]:
#3월 온도
temp['Mar']

np.int64(4)

In [21]:
#9월 온도
temp['Sep'] #error

KeyError: 'Sep'

#### 2) DataFrame 데이터프레임
2차원 배열구조 (1차원 배열이 여러개.. 즉, Series 들의 모음)

- **2차원 리스트**로 데이터프레임 생성

In [22]:
aaa= pd.DataFrame([ [10,20,30], [100,200,300], [1000,2000,3000] ])
print(aaa) # 세로번호 index, 가로번호 columns

      0     1     2
0    10    20    30
1   100   200   300
2  1000  2000  3000

In [23]:
#print()없이 값으로만 출력하면 더 이쁘게 출력됨
aaa

      0     1     2
0    10    20    30
1   100   200   300
2  1000  2000  3000

In [24]:
#행렬 구조의 컬룸명도 번호로 되어 있어서 식별이 이상하니..
#컬룸명 지정
aaa.columns= ['n1','n2','n3']
aaa

     n1    n2    n3
0    10    20    30
1   100   200   300
2  1000  2000  3000

In [25]:
#데이터 프레임 자료형 확인
print( type(aaa) )

<class 'pandas.core.frame.DataFrame'>

In [26]:
# 데이터 프레임의 행렬 모양을 확인하는 속성
print( aaa.shape ) #튜플(행,열)

(3, 3)

In [27]:
# 데이터프레임을 생성할때 columns, index 를 설정할 수 있음.
bbb= pd.DataFrame(data=[
    [10,20,30],
    [100,200,300],
    [1000,2000,3000]
], columns=['숫자1','숫자2','숫자3'], index=['가','나','다'])

bbb

    숫자1   숫자2   숫자3
가    10    20    30
나   100   200   300
다  1000  2000  3000

In [28]:
type(bbb)

pandas.core.frame.DataFrame

- **딕셔너리 타입**으로 데이터프레임 생성

In [29]:
ccc= pd.DataFrame({'aa':[10,20,30], 'bb':[100,200,300], 'cc':[1000,2000,3000]}) #식별자 key가 columns 명이 됨.
ccc

   aa   bb    cc
0  10  100  1000
1  20  200  2000
2  30  300  3000

- **csv 파일**로 데이터프레임 생성

In [30]:
students= pd.read_csv('./data_set/students.csv')
students

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73

In [31]:
#csv의 첫줄에 columns 명이 아닌경우.
students= pd.read_csv('./data_set/students_no_header.csv')
students

   손흥민  85  90  88
0  류현지  92  87  91
1  김민재  78  82  80
2  김연아  88  93  95
3  박세리  70  75  73

In [35]:
# csv를 읽으면서 첫줄을 컬룸명으로 인식하지 않도록 하면서 읽기
students= pd.read_csv(
    './data_set/students_no_header.csv', 
    header=None,
    names=['이름','국어','영어','수학'] #컬룸명 지정
)
students

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73

- **tsv 파일**로 데이터 프레임 생성

In [36]:
students= pd.read_csv('./data_set/students.tsv', sep='\t') # 구분자를 지정
students

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73

- **엑셀 파일**로 데이터프레임 생성

In [37]:
students= pd.read_excel('./data_set/students.xlsx')
students

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73

In [38]:
#데이터프레임의 행렬구조 확인
students.shape

(5, 4)

### 데이터를 Series 나 DataFrame 객체로 만드는 이유
시리즈나 데이터프레임을 사용하면 pandas 의 기초통계 기능(평균,최대,최소 등)들을 쉽게 사용할 수 있음.

#### 시리즈 사용 사례
예) 파이썬 교과목의 중간고사 점수 분포 분석

In [39]:
scores= pd.Series(
    [78, 85, 62, 90, 55, 88],
    index=['손흥민','김민재','박찬호','김연아','박세리','김동현']
)
scores

손흥민    78
김민재    85
박찬호    62
김연아    90
박세리    55
김동현    88
dtype: int64

In [40]:
#시리즈를 이용한 데이터 분석 맛보기
#기본 통계
print('평균:', scores.mean() )
print('최고점:', scores.max() )
print('최저점:', scores.min() )

평균: 76.33333333333333
최고점: 90
최저점: 55

In [41]:
#조건 필터링 (80점 이상) -- 불리언 인덱싱
passed= scores[ scores>=80 ]
passed

김민재    85
김연아    90
김동현    88
dtype: int64

#### 데이터프레임 사용 사례
예) 학생별 중간 / 기말 점수 성적 비교 및 종합 분석

In [42]:
#학생 성적 데이터
data = {
    "중간고사": [78, 85, 62, 90, 55, 88],
    "기말고사": [80, 88, 70, 92, 60, 90]
}

df = pd.DataFrame(
    data,
    index=["손흥민", "김민재", "박찬호", "김연아", "박세리", "김동현"]
)

df

     중간고사  기말고사
손흥민    78    80
김민재    85    88
박찬호    62    70
김연아    90    92
박세리    55    60
김동현    88    90

In [43]:
# 데이터프레임 기본 분석 맛보기

# 고사별 평균 확인
print('고사별 평균:')
print( df.mean() ) #데이터프레임의 전체 평균을 구하면 컬룸별 평균을 계산해줌.

고사별 평균:
중간고사    76.333333
기말고사    80.000000
dtype: float64

In [44]:
#학생별 평균을 구해서 새로운 컬룸에 저장하기
df['평균']= df.mean(axis=1) #축 - 평균을 가로방향으로 계산
print('학생별 평균이 추가된 데이터프레임')
df

학생별 평균이 추가된 데이터프레임

     중간고사  기말고사    평균
손흥민    78    80  79.0
김민재    85    88  86.5
박찬호    62    70  66.0
김연아    90    92  91.0
박세리    55    60  57.5
김동현    88    90  89.0

In [45]:
#조건부 필터링 + 정렬

# 평균 80점 이상인 고득점 학생만 선택하여 새로운 데이터프레임으로 생성
high_scores= df[ df['평균']>=80 ]
high_scores

     중간고사  기말고사    평균
김민재    85    88  86.5
김연아    90    92  91.0
김동현    88    90  89.0

In [47]:
#우수 학생 중 평균 점수 기준 내림차순 정렬
result= high_scores.sort_values(by='평균', ascending=False)
result

     중간고사  기말고사    평균
김연아    90    92  91.0
김동현    88    90  89.0
김민재    85    88  86.5

In [48]:
# 컬룸명만 확인
df.columns

Index(['중간고사', '기말고사', '평균'], dtype='object')

In [49]:
# 데이터프레임의 컬룸별 데이터타입들을 확인하고 싶다면.
df.dtypes

중간고사      int64
기말고사      int64
평균      float64
dtype: object

#### 판다스의 자료형 정리
- 문자열 str : **object**
- 정수 int : **int64**
- 실수 float : **float64**
- 논리값 bool : **bool**
- 날짜 datatime : **datatime64**

In [50]:
# 데이터프레임의 다양한 정보들을 확인하는 기능
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 손흥민 to 김동현
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   중간고사    6 non-null      int64
 1   기말고사    6 non-null      int64
 2   평균      6 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 364.0+ bytes

In [60]:
#기초통계 계산
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

## "데이터 분석은 데이터의 구조를 이해하는 것부터 시작한다."

In [55]:
# 책에 있는 대량의 데이터셋 불러오기 [ 갭마인더 tsv ]
df= pd.read_csv('./data/gapminder.tsv', sep='\t')
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [56]:
#1074 줄이나 되어 데이터가 너무 많이 보기 여러움. 그래서 상위 5개만 확인(데이터구조 확인)
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [57]:
# 마지막 5개
df.tail()

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [58]:
df.tail(n=7)

       country continent  year  lifeExp       pop   gdpPercap
1697  Zimbabwe    Africa  1977   57.674   6642107  685.587682
1698  Zimbabwe    Africa  1982   60.363   7636524  788.855041
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [59]:
#데이터의 대략적 특징 파악 이나 특정 연도의 1인당 GDP 순위 Top5 추출
df2002= df[ df['year']== 2002 ].sort_values('gdpPercap', ascending=False)
df2002.head()

            country continent  year  lifeExp        pop    gdpPercap
1150         Norway    Europe  2002   79.050    4535591  44683.97525
1618  United States  Americas  2002   77.310  287675526  39097.09955
1366      Singapore      Asia  2002   78.770    4197776  36023.10540
862          Kuwait      Asia  2002   76.904    2111561  35110.10566
1486    Switzerland    Europe  2002   80.620    7361757  34480.95771