# 데이터프레임에서 원하는 데이터를 추룰하기

In [1]:
import pandas as pd

In [2]:
data = [['김민재', 27, 75, 5428000],
['이강인', 22, 57, 3428000],
['박찬호', 50, 91, 8428000],
['차범근', 70, 80, 4428000],
['추신수', 43, 100, 4528000],
['손흥민', 31, 72, 7028000],
['황희찬', 28, 69, 2528000]]
df = pd.DataFrame(data, columns=['성명', '나이', '몸무게', '급여'])
df

    성명  나이  몸무게       급여
0  김민재  27   75  5428000
1  이강인  22   57  3428000
2  박찬호  50   91  8428000
3  차범근  70   80  4428000
4  추신수  43  100  4528000
5  손흥민  31   72  7028000
6  황희찬  28   69  2528000

In [4]:
#열(column) 데이터 추출
names = df['성명'] # Series 자료형으로 결과를 줌
names

0    김민재
1    이강인
2    박찬호
3    차범근
4    추신수
5    손흥민
6    황희찬
Name: 성명, dtype: object

In [6]:
type(names)

pandas.core.series.Series

In [7]:
#[]인덱싱 대신.컬룸명으로 추출도 가능함.
df.성명 # 가능하지만 자주쓰지 않는다.

0    김민재
1    이강인
2    박찬호
3    차범근
4    추신수
5    손흥민
6    황희찬
Name: 성명, dtype: object

In [8]:
#[] 안에 리스트 형태로 컬룸을 지정하면 결과를 DataFrame으로 줌
name_df=df[['성명']]
name_df

    성명
0  김민재
1  이강인
2  박찬호
3  차범근
4  추신수
5  손흥민
6  황희찬

In [9]:
type(name_df)

pandas.core.frame.DataFrame

In [10]:
#성명,급여 컬룸을 한번에 추출
name_salary_df=df[['성명','급여']]
name_salary_df

    성명       급여
0  김민재  5428000
1  이강인  3428000
2  박찬호  8428000
3  차범근  4428000
4  추신수  4528000
5  손흥민  7028000
6  황희찬  2528000

In [11]:
name_salary_df.shape

(7, 2)

In [12]:
#각 컬룸의 자료형 확인
name_salary_df.dtypes

성명    object
급여     int64
dtype: object

In [13]:
data_info_df = pd.DataFrame({
    '컬럼명': df.columns,
    '데이터타입': df.dtypes,
    '결측치수(NaN)': df.isnull().sum(),
    '고유값수': df.nunique()
})
data_info_df.reset_index(drop=True)

   컬럼명   데이터타입  결측치수(NaN)  고유값수
0   성명  object          0     7
1   나이   int64          0     7
2  몸무게   int64          0     7
3   급여   int64          0     7

In [14]:
# 4교시
# 행 데이터 추출
# 1. loc : index명으로 추출 location
# 2. iloc : index번호(행 위치 0,1,2,...)로 추출 integer location

In [15]:
df

    성명  나이  몸무게       급여
0  김민재  27   75  5428000
1  이강인  22   57  3428000
2  박찬호  50   91  8428000
3  차범근  70   80  4428000
4  추신수  43  100  4528000
5  손흥민  31   72  7028000
6  황희찬  28   69  2528000

In [16]:
#첫번째 데이타 추출
df.loc[0] #인덱스 명--결과 Series로 줌

성명         김민재
나이          27
몸무게         75
급여     5428000
Name: 0, dtype: object

In [17]:
#결과를 데이터프레임으로 ..
df.loc[[0]]

    성명  나이  몸무게       급여
0  김민재  27   75  5428000

In [18]:
#'차범근'의 데이터 추출
df.loc[[3]]

    성명  나이  몸무게       급여
3  차범근  70   80  4428000

In [19]:
#김민재, 이강인, 손흥민, 황희찬 데이터 추출
df.loc[[0,1,5,6]]

    성명  나이  몸무게       급여
0  김민재  27   75  5428000
1  이강인  22   57  3428000
5  손흥민  31   72  7028000
6  황희찬  28   69  2528000

In [20]:
#인덱스 번호와 명이 혼동되니 인덱스명을 새로 지정하기
df.index=['a','b','c','d','e','f','g']
df

    성명  나이  몸무게       급여
a  김민재  27   75  5428000
b  이강인  22   57  3428000
c  박찬호  50   91  8428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000
f  손흥민  31   72  7028000
g  황희찬  28   69  2528000

In [21]:
df.loc[[0]] # 0의 인덱스 명이 없어졌기 때문에 error

KeyError: "None of [Index([0], dtype='int64')] are in the [index]"

In [22]:
df.loc[['a']]

    성명  나이  몸무게       급여
a  김민재  27   75  5428000

In [23]:
#인덱스번호(행 위치번호)로 추출 iloc
df

    성명  나이  몸무게       급여
a  김민재  27   75  5428000
b  이강인  22   57  3428000
c  박찬호  50   91  8428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000
f  손흥민  31   72  7028000
g  황희찬  28   69  2528000

In [24]:
#김민재 데이터를 행번호로 찾기
df.iloc[0]

성명         김민재
나이          27
몸무게         75
급여     5428000
Name: a, dtype: object

In [25]:
df.iloc[[0]]

    성명  나이  몸무게       급여
a  김민재  27   75  5428000

In [26]:
#박찬호 추신후 ,황희찬 데이타 추출
df.iloc[[2,4,6]]

    성명  나이  몸무게       급여
c  박찬호  50   91  8428000
e  추신수  43  100  4528000
g  황희찬  28   69  2528000

In [27]:
#마지막 행의 데이터 추출
df.iloc[[-1]]

    성명  나이  몸무게       급여
g  황희찬  28   69  2528000

In [28]:
df.iloc[[-3]]

    성명  나이  몸무게       급여
e  추신수  43  100  4528000

In [29]:
#이강인 부터 시작해서 추신수까지 데이터를 모두 추출 -- 슬라이싱.. 할때는 무조건 []가 1개 -- 이미 dataframe임
df.iloc[1:5] #1~4까지

    성명  나이  몸무게       급여
b  이강인  22   57  3428000
c  박찬호  50   91  8428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000

In [30]:
#인덱스명으로 슬라이싱
df['b':'e'] # 시작명, 끝명 ( 마지막 인덱스명까지 포함)

    성명  나이  몸무게       급여
b  이강인  22   57  3428000
c  박찬호  50   91  8428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000

In [31]:
# 행, 열 모두를 지정하여 선택하기.
# loc[[행],[열]]
# iloc[[행번호],[열번호]]

In [32]:
# 'a'행의 '성명'데이타 추출
df.loc[['a'],['성명']]

    성명
a  김민재

In [34]:
# c행의 성명,나이 데이터만 추출
df.loc[['c'],['성명','나이']]

    성명  나이
c  박찬호  50

In [35]:
#이강인 추신수 손흥민의 나이와 급여 추출
df.loc[['b','e','f'],['나이','급여']]

   나이       급여
b  22  3428000
e  43  4528000
f  31  7028000

In [36]:
#이강인부터 추신수까지 성명, 급여 추출 -슬라이싱
df.loc['b':'e',['성명','급여']] # 슬라이싱 자체가 이미 dataframe이니. []를 안써도 됨

    성명       급여
b  이강인  3428000
c  박찬호  8428000
d  차범근  4428000
e  추신수  4528000

In [37]:
#처음부터 차법근까지 성명 나이 급여 추출
df.loc[:'d',['성명','나이','급여']]

    성명  나이       급여
a  김민재  27  5428000
b  이강인  22  3428000
c  박찬호  50  8428000
d  차범근  70  4428000

In [38]:
#처음부터 끝까지 급여만 추출 
df.loc[:,['급여']]

        급여
a  5428000
b  3428000
c  8428000
d  4428000
e  4528000
f  7028000
g  2528000

In [39]:
#iloc 사용
# 3번째 줄의 성명,급여 추출
df.iloc[[2],['성명','급여']] # 컬룸명도 컬룸번호를 써야함.

IndexError: .iloc requires numeric indexers, got ['성명' '급여']

In [40]:
# df.iloc[[2],['성명','급여']] # 컬룸명도 컬룸번호를 써야함.
df.iloc[[2],[0,3]] # 컬룸명도 컬룸번호를 써야함.

    성명       급여
c  박찬호  8428000

In [41]:
# 급여 컬룸의 경우는 마지막 위치임..
df.iloc[[2,5,6],[0,-1]] # 0:처음 -1: 마지막

    성명       급여
c  박찬호  8428000
f  손흥민  7028000
g  황희찬  2528000

In [42]:
#박찬호부터 끝행까지 .. 성명부터 몸무게까지 추출 -슬라이싱
# df.iloc[2:,0:3] # 행번호는 2~ 부터,, 컬룸번호 0~2 0부터 2까지
df.iloc[2:, :3]

    성명  나이  몸무게
c  박찬호  50   91
d  차범근  70   80
e  추신수  43  100
f  손흥민  31   72
g  황희찬  28   69

In [43]:
#박찬호부터 끝행까지 .. 성명부터 몸무게까지 추출 -슬라이싱
# df.iloc[2:,0:3] # 행번호는 2~ 부터,, 컬룸번호 0~2 0부터 2까지
# df.iloc[2:, :3]
df.iloc[2:,:-1]

    성명  나이  몸무게
c  박찬호  50   91
d  차범근  70   80
e  추신수  43  100
f  손흥민  31   72
g  황희찬  28   69

### [분석 연습]

In [47]:
# 축구 선수들의 급여 평균, 야구선수들의 급여 평균
football_df=df.iloc[[0,1,3,5,6],:] # : - 시작 부터 끝까지
football_df['급여'].mean()

np.float64(4568000.0)

In [48]:
baseball_df=df.iloc[[2,4],:]
baseball_df['급여'].mean()

np.float64(6478000.0)

In [49]:
#조건에 맞는 데이터만 추출해보기

In [50]:
#급여가 5000000원 이상인 고객연봉자 추출--불리언 인덱싱
df['급여']>5000000

a     True
b    False
c     True
d    False
e    False
f     True
g    False
Name: 급여, dtype: bool

In [51]:
#booleam 값을 가진 시지르의 요소중에서  true인 요소만 선택하여 새로운 데이터프렘임 생성

In [52]:
high_salary_df=df.loc[df['급여']>5000000]
high_salary_df

    성명  나이  몸무게       급여
a  김민재  27   75  5428000
c  박찬호  50   91  8428000
f  손흥민  31   72  7028000

In [53]:
df[df['급여']>5000000]

    성명  나이  몸무게       급여
a  김민재  27   75  5428000
c  박찬호  50   91  8428000
f  손흥민  31   72  7028000

In [57]:
#조건이 2개 이상인 것들... 급여가 500만 이상이고, 나이가 40세 미만
(df['급여']>5000000)&(df['나이']<40)  # 비트연산자

a     True
b    False
c    False
d    False
e    False
f     True
g    False
dtype: bool

In [55]:
#조건에 맞는 사람의 셩명,나이,급여 만 추출하여 새로운 데이터프레임 만들기 
young_rich_df = df.loc[(df['급여']>5000000)&(df['나이']<40), ['성명','나이','급여']]
young_rich_df

    성명  나이       급여
a  김민재  27  5428000
f  손흥민  31  7028000

In [56]:
#or 조건... 둘중에 하나라도 만족하면..
#나이가 40이상이거나.. 몸무게가 80kg 이상인 사람들 '내시경 필수 검진 대상자'

(df['나이']>=40)|(df['몸무게']>=80)   # 비트연산자 |

a    False
b    False
c     True
d     True
e     True
f    False
g    False
dtype: bool

In [59]:
#내시경 필수 검진 대상자 추출
checkup_df = df.loc[(df['나이']>=40)|(df['몸무게']>=80)]
checkup_df

    성명  나이  몸무게       급여
c  박찬호  50   91  8428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000

In [60]:
#NOT(~) 급여가 평균 이상이 아닌 경우(평균 미만인 경우)
~(df['급여']>=df['급여'].mean())

a    False
b     True
c    False
d     True
e     True
f    False
g     True
Name: 급여, dtype: bool

In [61]:
#평균 급여에 미치지 못하는 선수들 추출 
low_salary= df.loc[~(df['급여']>=df['급여'].mean())]
low_salary

    성명  나이  몸무게       급여
b  이강인  22   57  3428000
d  차범근  70   80  4428000
e  추신수  43  100  4528000
g  황희찬  28   69  2528000

In [63]:
#특정조건에 해당할때 새로운 컬룸에 식별글씨 저장하기
df.loc[df['몸무게']>90,['체질량']]='비만'
df

    성명  나이  몸무게       급여  체질량
a  김민재  27   75  5428000  NaN
b  이강인  22   57  3428000  NaN
c  박찬호  50   91  8428000   비만
d  차범근  70   80  4428000  NaN
e  추신수  43  100  4528000   비만
f  손흥민  31   72  7028000  NaN
g  황희찬  28   69  2528000  NaN