## 데이터 프레임 구조 변경 및 저장
1. DataFrame에 새로운 컬룸을 추가하거나 원하는 자료형으로 변환하는 등의 조작.
2. DataFrame 객체를 csv,excel등의 파일로 저장 및 열기

세상에는 완전한 데이타셋이 존재하지 않는다. 지금은 LLM에 줘 하면 그냥 주는데 우리 데이타 셋을 기반으로 tool을 주어 AI가 만들어 주게 해야 함. 추천을 하게 함. 파이프라인을 구축한다고 한다. 사용자에게 줄 데이타를 문맥정보를 행동 패턴으로 LLM에게 줘야 하는데 그 정보도 우리가 만들어 주어야 함다.

In [1]:
# 데이터 프레임 만들기 - 모든 작업의 시작
import pandas as pd   # 계산기 같은 개념
data = {
    '이름' : ['손흥민', '김민재', '이강인', '황의찬', '류현진', '김병현', '박찬호', '추신수'],
    '학교' : ['축구고', '축구고', '축구고', '축구고', '야구고', '야구고', '야구고', '야구고'],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90]
}

df = pd.DataFrame(data) # 인덱스 자동 0,1,
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [2]:
#인덱스 변경해 보기
df.index = ['1번','2번','3번','4번','5번','6번','7번','8번']
df

     이름   학교   국어   영어   수학
1번  손흥민  축구고   90   85  100
2번  김민재  축구고   40   35   50
3번  이강인  축구고   80   75   70
4번  황의찬  축구고   40   60   70
5번  류현진  야구고   15   20   10
6번  김병현  야구고   80  100   95
7번  박찬호  야구고   55   65   45
8번  추신수  야구고  100   85   90

In [3]:
#인덱스 컬륨에 컬룸명을 설정하기  - groupby는 이것을 자동으로 해줌. 우리는 groupby를 만들어 보는 것이다.
df.index.name = '학생번호'
df

       이름   학교   국어   영어   수학
학생번호
1번    손흥민  축구고   90   85  100
2번    김민재  축구고   40   35   50
3번    이강인  축구고   80   75   70
4번    황의찬  축구고   40   60   70
5번    류현진  야구고   15   20   10
6번    김병현  야구고   80  100   95
7번    박찬호  야구고   55   65   45
8번    추신수  야구고  100   85   90

In [4]:
#굳이 인덱스명을 학생번호로 안해도 될것 같아.. 그래서 원래대로 0,1,2...인덱스를 초기화 
df.reset_index() # 인덱스를 초기화함.

  학생번호   이름   학교   국어   영어   수학
0   1번  손흥민  축구고   90   85  100
1   2번  김민재  축구고   40   35   50
2   3번  이강인  축구고   80   75   70
3   4번  황의찬  축구고   40   60   70
4   5번  류현진  야구고   15   20   10
5   6번  김병현  야구고   80  100   95
6   7번  박찬호  야구고   55   65   45
7   8번  추신수  야구고  100   85   90

In [5]:
#reset_index()를 하면 기존 인덱스로 쓰면 컬룸들이 데이터용 컬룸으로 변경됨
#만약, 이 학생번호가 데이터로서 필요없다면.. reset_index()할때 기존 인덱스용 컬룸들을 제거하도록
df.reset_index(drop=True)

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [6]:
# 위 리셋기능작업을 수행하면 원본 데이터프레임은 그대로 있고.
#변경된 새로운 데이터 프레임이 출력되었던 것임
# 그래서 현재 데이터프레임을 출력해보면.. 위 reset_index()작업이 반영되어 있지 않음. 
df

       이름   학교   국어   영어   수학
학생번호
1번    손흥민  축구고   90   85  100
2번    김민재  축구고   40   35   50
3번    이강인  축구고   80   75   70
4번    황의찬  축구고   40   60   70
5번    류현진  야구고   15   20   10
6번    김병현  야구고   80  100   95
7번    박찬호  야구고   55   65   45
8번    추신수  야구고  100   85   90

In [7]:
# reset_index()를 수행할때 원본 데이터프레임에 적용도게 하려면... # inplace
df.reset_index(drop=True, inplace=True)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [8]:
# 새로운 인덱스를 지정할건데...특정 컬룸의 값으로  인덱스명으로 사용하도록 변경
df.set_index('이름',inplace=True)
df

      학교   국어   영어   수학
이름
손흥민  축구고   90   85  100
김민재  축구고   40   35   50
이강인  축구고   80   75   70
황의찬  축구고   40   60   70
류현진  야구고   15   20   10
김병현  야구고   80  100   95
박찬호  야구고   55   65   45
추신수  야구고  100   85   90

In [9]:
#인덱스명을 기준으로 오름차훈 또는 내림차순으로 정렬가능
df.sort_index() # inplace를 사용하지 않으면 원본은 그대로

      학교   국어   영어   수학
이름
김민재  축구고   40   35   50
김병현  야구고   80  100   95
류현진  야구고   15   20   10
박찬호  야구고   55   65   45
손흥민  축구고   90   85  100
이강인  축구고   80   75   70
추신수  야구고  100   85   90
황의찬  축구고   40   60   70

In [10]:
df.sort_index(ascending=True)

      학교   국어   영어   수학
이름
김민재  축구고   40   35   50
김병현  야구고   80  100   95
류현진  야구고   15   20   10
박찬호  야구고   55   65   45
손흥민  축구고   90   85  100
이강인  축구고   80   75   70
추신수  야구고  100   85   90
황의찬  축구고   40   60   70

In [11]:
# 인덱스를 다시 지정하여 원위치..
df.reset_index(inplace=True)
df   # 다시 처음으로 돌아옴 원본이...

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

### 새로운 컬룸 추가

In [12]:
#데이터세세 평균 점수를 저장되어 있지 않음. 분석할때마다 평균계산하지 말고 .. 학생별 평균컬룸을 만들기.
# 데이터프레임 자체에 통으로 평균계산 가능
# df['국어'].mean()
df.mean()
df

TypeError: Could not convert ['축구고축구고축구고축구고야구고야구고야구고야구고'] to numeric

In [ ]:
#데이터프레임의 컬룸들 중에서 숫자데이터만 평균을 계산
df[['국어','영어','수학']].mean()

In [ ]:
# 학생별 평균을 구하기 위해 평균계산을 가로방향으로 하도록....
df[['국어','영어','수학']].mean(axis=1)   # axis=1 가로방향

In [ ]:
#평균값 시리즈를 원래 데이터프레임의 '평균'칸을 새로 만들어 추가 
df['평균']=df[['국어','영어','수학']].mean(axis=1)
df

In [ ]:
#평균을 소수점 2자리까지만 표기 
df['평균']=df[['국어','영어','수학']].mean(axis=1).round(2)
df

In [ ]:
#'총점'컬룸 추가하기
# df['컬룸']=df[['국어','영어','수학']].sum(axis=1)  # 아래와 같다 . 
df['컬룸']=df[['국어','영어','수학']].sum(axis='columns') 
df 

#기존의 데이타를 가지고 새로운 것을 만들어 내는것이 특성공학