## 판다스는 문자열로 구성된 데이터에서 특정 문자열의 분할 , 변경, 대체, 제거 등의 작업 가능
- str.split()
- str.upper()
- str.replace()
- str.contains() # 특정 글자 있는지 ..
- str.strip()

In [1]:
import pandas as pd
data = [['김예찬', 'm', '부장', '010-1234-5678', '서울시 강남구 삼성동'],
        ['이하은', 'f', '인턴', '010-8765-4321', '부산시 해운대구 우동'],
        ['박지현', 'f', '과장', '010-1357-2468', '대구시 수성구 범어동'],
        ['최준호', 'm', '임시', '010-1928-3746', '인천시 연수구 송도동'],
        ['김예서', 'f', '과장', '010-2846-5937', '천안시 서북구 두정동']
]
df= pd.DataFrame(data)
df.columns = ['성명', '성별', '직급', '전화번호', '주소']
df

    성명 성별  직급           전화번호           주소
0  김예찬  m  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  f  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  f  과장  010-1357-2468  대구시 수성구 범어동
3  최준호  m  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  f  과장  010-2846-5937  천안시 서북구 두정동

In [7]:
# '성별' 컬룸에 있는 글씨를 대문자로 변경
df['성별']=df['성별'].str.upper()  # object 이니. 그냥못씀. ,, 그리고 원본은 안바뀜
df

    성명 성별  직급           전화번호           주소
0  김예찬  M  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  F  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  F  과장  010-1357-2468  대구시 수성구 범어동
3  최준호  M  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  F  과장  010-2846-5937  천안시 서북구 두정동

In [8]:
#M-->male , F-->female 로 변경
df['성별'] = df['성별'].str.replace('M','male')
df['성별'] = df['성별'].str.replace('F','female')
df

    성명      성별  직급           전화번호           주소
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  female  인턴  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
3  최준호    male  임시  010-1928-3746  인천시 연수구 송도동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [12]:
# 바꿀 데이타가 많으면 어떻게 할꺼냐 ,, Or
# '직급'에서 '인턴', '임시'를 '사원'으로 변경
df['직급'] = df['직급'].str.replace('인턴|임시','사원',regex=True) # 정규표현식을 사용해야 |연산 가능 ... 정규식 표현 : 웹에서 유효성 검사 때 배움 
df

    성명      성별  직급           전화번호           주소
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [13]:
# '성별'컬룸에서 '여성'을 찾기.. 있으면 True, 없으면 False
df['성별'].str.contains('female')

0    False
1     True
2     True
3    False
4     True
Name: 성별, dtype: bool

In [15]:
#누군지 확인하기 위해 여성 데이터들만(True)인 요소들만 찾아서 추출 -- 불리언 인덱싱 [ true / false가지고 선택 ]
df[df['성별'].str.contains('female')]

    성명      성별  직급           전화번호           주소
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동

In [22]:
#지역, 주소는 서울시, 서울특별시.. 그리고 길이도 다르고..  그리고 같은 이름이 지역마다 있음... 
# 그래서 도시만 빼오자.. 앞에서만 
#문자열의 슬라이싱 기능
# 주소에서 도시명만 추출하여 도시컬룸 생성
df['도시']=df['주소'].str[0:4]  # 문자열 슬라이싱  [0] 은 인덱싱  -> 띄어쓰기까지 포함되었는데 보여지는 것은 구분이 안됨
df

    성명      성별  직급           전화번호           주소    도시
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동  인천시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [23]:
#도시 중에서 서울시만 추출
seoul_df=df[ df['도시']=='서울시']
seoul_df

Empty DataFrame
Columns: [성명, 성별, 직급, 전화번호, 주소, 도시]
Index: []

In [25]:
aa=df.loc[0,'도시'] # 행명(인덱스명), 컬룸명 -> 숫자 아님.
aa # 글자로 ''로 나옴.  aa=df.loc[ [0],'도시'] 는 문자열로 안됨

'서울시 '

In [26]:
aa=='서울시'

False

In [27]:
aa.strip() == '서울시'

True

In [29]:
df['도시'] = df['도시'].str.strip()
df

    성명      성별  직급           전화번호           주소   도시
0  김예찬    male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
3  최준호    male  사원  010-1928-3746  인천시 연수구 송도동  인천시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [30]:
seoul_df=df[ df['도시']=='서울시']
seoul_df

    성명    성별  직급           전화번호           주소   도시
0  김예찬  male  부장  010-1234-5678  서울시 강남구 삼성동  서울시

In [32]:
#5교시 
# 특정 값들을 가진 파이썬 리스트의 항목을 가진 행들을 추출
cities = ['서울시','인천시']
seoul_incheon_df=df[df['도시'].isin(cities)]
seoul_incheon_df

    성명    성별  직급           전화번호           주소   도시
0  김예찬  male  부장  010-1234-5678  서울시 강남구 삼성동  서울시
3  최준호  male  사원  010-1928-3746  인천시 연수구 송도동  인천시

In [34]:
#서울,인천을 제외한 모든 도시들 추출 [ ~ Not 틸드 ] 
not_seoul_incheon_df = df[~(df['도시'].isin(cities))]
not_seoul_incheon_df

    성명      성별  직급           전화번호           주소   도시
1  이하은  female  사원  010-8765-4321  부산시 해운대구 우동  부산시
2  박지현  female  과장  010-1357-2468  대구시 수성구 범어동  대구시
4  김예서  female  과장  010-2846-5937  천안시 서북구 두정동  천안시

In [36]:
# 특정 글씨로 시작하는 ...
# df[df['성명'].str.contains] # 이것은 포함하는 것이지 시작하는 것은 아님
df[df['성명'].str.startswith('최')] #최로 시작하는...  endswith도 있다... 이것은 책의 11챕터  4챕터 그림그리는 것은 넘어갈 것이다. 5챕터로 가자.

    성명    성별  직급           전화번호           주소   도시
3  최준호  male  사원  010-1928-3746  인천시 연수구 송도동  인천시