In [1]:
import pandas as pd

In [8]:
aa = pd.Series([10,20,30],dtype='int64',index=['a','b','c'])

In [3]:
type(aa)

pandas.core.series.Series

In [10]:
aa

a    10
b    20
c    30
dtype: int64

In [14]:
aa['a']
print(type(aa))
print(aa.shape)

<class 'pandas.core.series.Series'>
(3,)

In [18]:
data = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
data.columns =['n1','n2','n3']
data

   n1  n2  n3
0   1   2   3
1   4   5   6
2   7   8   9

In [23]:
data = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['숫자1','숫자2','숫자3'],index=['가','나','다'])
data

   숫자1  숫자2  숫자3
가    1    2    3
나    4    5    6
다    7    8    9

In [25]:
ccc = pd.DataFrame({'col1':[10,20,30],'col2':[11,21,31]})
ccc

   col1  col2
0    10    11
1    20    21
2    30    31

In [26]:
stu = pd.read_csv('./data_set/students.csv')
stu

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73

In [30]:
students = pd.read_csv('./data_set/students_no_header.csv',header=None,names=['이름','국어','영어','수학'])
students

    이름  국어  영어  수학
0  손흥민  85  90  88
1  류현지  92  87  91
2  김민재  78  82  80
3  김연아  88  93  95
4  박세리  70  75  73